resolve #103 add analytics tab
Boticot/boticot pull request #104
Opened 2021-08-23 10:21 UTC by amirensit

resolve #103 add analytics tab

2021-09-13 09:40 UTC, omar-mellouli commented on admin/package.json
>      "@types/chai": "^4.2.11",
While jest is used, don't need to remove this dependency ?

2021-09-13 12:29 UTC, omar-mellouli commented on admin/src/__tests__/Analytics.spec.ts
> +  describe('Testing methods', () => {
To delete

2021-09-16 17:00 UTC, omar-mellouli requested changes

2021-09-16 17:08 UTC, omar-mellouli commented on admin/src/views/Analytics.vue
> +    const handleIntentLegendClick = function (this: any, e, legendItem) {
why inside data ?

2021-09-16 17:08 UTC, omar-mellouli commented on admin/src/views/Analytics.vue
> +      dateFields: '',
use Data or DataList (or another thing if you have suggestion) instead of Fields for all variables

2021-09-17 06:41 UTC, amirensit commented on admin/src/__tests__/App.spec.ts
> +});
This test is removed because the mock instance cannot be mocked when used whith routing.

2021-09-17 06:51 UTC, amirensit commented on admin/tsconfig.json
> +    "target": "es5",
Jest testing requires at least es5 as target.

2021-09-17 07:29 UTC, amirensit commented on admin/tsconfig.json
> +    "lib": ["es7", "dom"],
we need to explicitly set 'noImplicitAny': false in order to solve this issue
> TypeScript will fall back to a type of any for a variable when it cannot infer the type.

2021-09-17 08:08 UTC, amirensit commented on admin/tsconfig.json
> +  "exclude": ["node_modules"]
"exclude": ["node_modules"] already exist.

2021-09-17 08:11 UTC, amirensit commented on admin/tsconfig.json
> +  "include": ["src"],
In order for tests to succeed, we need to include **src** folder for typescript scanning.

2021-09-17 08:17 UTC, amirensit commented on admin/src/vue.shims.d.ts
> +declare module '*.vue' {
yes, it helps the IDE to understand what a file ending in .vue is.

2021-09-17 08:46 UTC, amirensit commented on admin/src/views/Analytics.vue
> +              ...colorsArray, ...colorsArray,
The number of intents may exceed the number of colors, so we need to increase the number of colors.

2021-09-17 14:32 UTC, omar-mellouli commented on admin/src/views/Analytics.vue
> +    getRandomColor() {
move to utils

2021-09-17 14:32 UTC, omar-mellouli commented on admin/src/views/Analytics.vue
> +      } else {
manage explicitly case of last 30 days

2021-09-17 14:32 UTC, omar-mellouli commented on admin/src/views/Analytics.vue
> +      if (value === 'Last day') limitedResult = _.takeRight((this.analyticsData as any).analytics, 1);
manage explicitly case of last 30 days

2021-09-17 14:32 UTC, omar-mellouli commented on admin/src/views/Analytics.vue
> +      const flatAnalyticsData = _.flatMap(limitedAnalyticsData, 'intents_count');
lot of constants ! you use chaining
you can do that:

const intentsDatasets = _(limitedAnalyticsData)
        .flatMap('intents_count')
        .uniqBy('intent')
        .map((item: any) => ({
          label: item.intent,
          data: this.getCountsOfIntent(item.intent, limitedAnalyticsData),
          fill: false,
          borderColor: this.getRandomColor(),
          tension: 0.1,
        }))
        .value();

2021-09-19 12:26 UTC, amirensit commented
There is a problem with Jest. When tests are run separetly, It works, but when the whole tests are run, it fails.

2021-09-24 16:37 UTC, omar-mellouli commented on admin/src/service/analyticsService.ts
> +      label: 'FALLBACK',
typo: Fallback

2021-09-24 16:37 UTC, omar-mellouli commented on admin/tsconfig.json
> +}
add line

2021-09-29 15:42 UTC, omar-mellouli commented on admin/src/client/__mocks__/mockedAnalyticsData.json
> +  }
add new line

2021-09-29 15:42 UTC, omar-mellouli commented on admin/src/__tests__/service/analyticsService.spec.ts
> +describe('analyticsService.ts', () => {
typo: analyticsService.ts

2021-09-29 15:42 UTC, omar-mellouli commented on admin/src/__tests__/service/analyticsService.spec.ts
> +  it('prepareAnalyticsData()', () => {
should prepare analytics data

2021-09-29 15:42 UTC, omar-mellouli commented on admin/src/__tests__/store/store.spec.ts
> +describe('Testing store', () => {
typo: store.ts

2021-09-29 15:42 UTC, omar-mellouli commented on admin/src/__tests__/store/store.spec.ts
> +  describe('testing getters', () => {
typo: Testing getters

2021-09-29 15:42 UTC, omar-mellouli commented on admin/src/__tests__/store/store.spec.ts
> +    it('initAgents', () => {
should update agents of state when call initAgents

2021-10-12 12:58 UTC, merged