resolves #105 add api to delete an intent associated to an agent
Boticot/boticot pull request #106
Opened 2021-08-24 09:43 UTC by elisaMy

2021-09-06 12:03 UTC, omar-mellouli commented on api/agents_service.py
> +        """ Delete an intent associated to an agent """
Remove useless comment

2021-09-06 12:04 UTC, omar-mellouli requested changes

2021-09-06 12:04 UTC, omar-mellouli commented on api/persistence/agents_repository.py
> +        """Delete an agent intent"""
Remove useless comment

2021-09-06 12:11 UTC, omar-mellouli commented on api/persistence/training_data_repository.py
> +    def delete_intent_training_data(self, agent_name, intent_name):
rename:
delete_agent_training_data_by_intent

2021-09-06 12:12 UTC, omar-mellouli commented on api/persistence/responses_repository.py
> +    def delete_intent_responses(self, agent_name, intent_name):
rename:
delete_agent_responses_by_intent

2021-09-06 15:07 UTC, elisaMy commented on api/agents_service.py
> +        """ Delete an intent associated to an agent """
Done

2021-09-06 15:08 UTC, elisaMy commented on api/persistence/agents_repository.py
> +        """Delete an agent intent"""
Done

2021-09-06 15:09 UTC, elisaMy commented on api/persistence/training_data_repository.py
> +    def delete_intent_training_data(self, agent_name, intent_name):
Done

2021-09-06 15:11 UTC, elisaMy commented on api/persistence/responses_repository.py
> +    def delete_intent_responses(self, agent_name, intent_name):
Done

2021-09-07 08:45 UTC, omar-mellouli approved these changes

2021-09-07 08:46 UTC, merged