resolves #111 add api to manage synonyms
Boticot/boticot pull request #112
Opened 2021-09-22 15:32 UTC by elisaMy

2021-11-22 10:34 UTC, omar-mellouli requested changes

2021-11-22 10:34 UTC, omar-mellouli commented on tests/api/test_agents_service.py
> +    def test_should_return_true_when_is_valid_returns_true_and_find_synonym_returns_something(self, mocker):
rename like:
test_should_synonym_exist_when_find_synonym_returns_something

2021-11-22 10:34 UTC, omar-mellouli commented on tests/api/test_agents_service.py
> +    def test_should_return_false_when_is_valid_returns_true_and_find_synonym_returns_none(self, mocker):
rename like:
test_should_synonym_not_exist_when_find_synonym_returns_none

2021-11-22 10:34 UTC, omar-mellouli commented on tests/api/test_agents_service.py
> +    def test_should_return_false_when_is_valid_returns_false_and_find_synonym_returns_something(self, mocker):
rename like:
test_should_synonym_not_exist_when_id_is_not_valid

2021-11-23 09:47 UTC, elisaMy commented on api/persistence/synonyms_repository.py
>      def delete_synonyms(self, agent_name):
done

2021-11-23 09:47 UTC, elisaMy commented on api/persistence/synonyms_repository.py
> +    def delete_synonym_by_id(self, agent_name, id):
done

2021-11-23 09:48 UTC, elisaMy commented on api/persistence/synonyms_repository.py
> +            return False
done

2021-11-23 09:48 UTC, elisaMy commented on tests/api/test_agents_service.py
> +    def test_should_return_true_when_is_valid_returns_true_and_find_synonym_returns_something(self, mocker):
done

2021-11-23 09:48 UTC, elisaMy commented on tests/api/test_agents_service.py
> +    def test_should_return_false_when_is_valid_returns_true_and_find_synonym_returns_none(self, mocker):
done

2021-11-23 09:48 UTC, elisaMy commented on tests/api/test_agents_service.py
> +    def test_should_return_false_when_is_valid_returns_false_and_find_synonym_returns_something(self, mocker):
done

2021-12-23 11:47 UTC, omar-mellouli commented on api/routes/synonym.py
> +        return response_template(400, "A body is mandatory inside the request")
Add new line

2021-12-23 14:28 UTC, elisaMy commented on api/routes/synonym.py
> +        return response_template(400, "A body is mandatory inside the request")
Done

2021-12-24 09:01 UTC, merged